#!/bin/sh

distro=$(lsb_release -i |  cut -d':' -f2)
release=$(lsb_release -c |  cut -d':' -f2)

check_redis_running() {
    redis-cli echo "just checking" > /dev/null
    return $?
}

check_redis_version() {

	version=$(redis-cli --version | cut -d' ' -f2)
	if [ $distro = "Debian" ]; then
		dpkg --compare-versions $version "<=" 2.8.6
	fi
	return $?
}

# Quit early if Redis server isn't running
if ! check_redis_running; then
    echo "[ERROR] Redis not running." >&2
    exit 2
fi

# Check redis package version on Debian
if check_redis_version; then
	echo "[WARN] You are using Redis $version (< 2.8.6). Some RQ fonctions may not work !"
fi

if command -v rg >/dev/null; then
    safe_rg=rg
else
    # Fall back for systems that don't have rg installed
    safe_rg=cat
fi

export ONLY_RUN_FAST_TESTS=1
if [ "$1" = '-f' ]; then  # Poor man's argparse
    unset ONLY_RUN_FAST_TESTS
    shift 1
fi

# For use on build server, we need exit code to be representative of success/failure
if [ "$1" = '-x' ]; then
    shift 1
    /usr/bin/env python -m unittest discover -v -s tests $@ 2>&1
else
    /usr/bin/env python -m unittest discover -v -s tests $@ 2>&1 | egrep -v '^test_' | $safe_rg
fi
