#!/bin/sh
check_redis_running() {
    redis-cli echo "just checking" > /dev/null
    return $?
}

# Quit early if Redis server isn't running
if ! check_redis_running; then
    echo "Redis not running." >&2
    exit 2
fi

export RUN_SLOW_TESTS_TOO=1
if [ "$1" = '-f' ]; then  # Poor man's argparse
    unset RUN_SLOW_TESTS_TOO
    shift 1
fi

/usr/bin/env python -m pytest -v tests $@ 2>&1
