# -*- coding: utf-8 -*-
#
# Copyright 2020 NVIDIA Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
from typing import Any, ContextManager


class BaseTimeoutException(Exception): ...
class JobTimeoutException(BaseTimeoutException): ...
class HorseMonitorTimeoutException(BaseTimeoutException): ...

class BaseDeathPenalty(ContextManager):
    _timeout: Any = ...
    _exception: Any = ...
    def __init__(self, timeout: Any, exception: Any = ..., **kwargs: Any) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, type: Any, value: Any, traceback: Any): ...
    def setup_death_penalty(self) -> None: ...
    def cancel_death_penalty(self) -> None: ...

class UnixSignalDeathPenalty(BaseDeathPenalty):
    def handle_death_penalty(self, signum: Any, frame: Any) -> None: ...
    def setup_death_penalty(self) -> None: ...
    def cancel_death_penalty(self) -> None: ...
